[package]
name = "mesad"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "mesad"
path = "src/main.rs"

[dependencies]
mesa-core-types = { workspace = true }
mesa-driver-manager = { workspace = true }
mesa-config-store = { workspace = true }
mesa-core-api = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde_json = { workspace = true }
