[package]
name = "mesa-config-store"
version.workspace = true
edition.workspace = true

[dependencies]
mesa-core-types = { workspace = true }
rusqlite = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
getrandom = { workspace = true }
