[package]
name = "mesa-driver-simulator"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "mesa_driver_simulator"
path = "src/lib.rs"

[[bin]]
name = "mesa-driver-simulator"
path = "src/main.rs"

[dependencies]
mesa-core-types = { workspace = true }
mesa-driver-sdk = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
async-trait = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
