[package]
name = "mesa-test-driver"
version.workspace = true
edition.workspace = true
license.workspace = true

rust-version.workspace = true
[lib]
name = "mesa_test_driver"
path = "src/lib.rs"

[[bin]]
name = "mesa-test-driver"
path = "src/main.rs"

[dependencies]
mesa-core-types = { workspace = true }
mesa-driver-sdk = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
async-trait = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
